### ISSUE TITLE
Lag when looking at blocks

### ISSUE THREAD

**Issue by Minx-Jinx** [ChaoticTrials/Excavar#10]
### Minecraft version

1.19.1

### Excavar version

1.19.1-2.1.1

### Forge version

42.0.1

### The latest.log file

https://imgur.com/a/6lBzedo

### Issue description

When Excavar is installed, when you look at any blocks, FPS drops considerably. Example being in a modpack, FPS drops from 150 to 5, or with only Excavar installed drops from 150 to 20.

### Steps to reproduce

Install latest Excavar version.
Make and enter singleplayer world.
Look at a block.

**Comment by MelanX** [comment]
Thank you!
