### ISSUE TITLE
Add the ability to take away xp when vein mining instead of hunger as well as being able to use both at the same time.

### ISSUE THREAD

**Issue by HighQualityShadows** [ChaoticTrials/Excavar#13]
### Describe your idea

Looking to be able to use this in my modpack but the above feature would be required.

**Comment by Randalkobolt** [comment]
Note: the modpack is for forge 1.20.1

**Comment by Randalkobolt** [comment]
Alright thanks for all the changes, however the minimum for the xp value is set too high, it would be better if you could set it lower to like 0.1 or 0.25 xp per block.

**Comment by Randalkobolt** [comment]
Making a separate issue for this.
