### ISSUE TITLE
Block Highlighting doesn't take durability into consideration 

### ISSUE THREAD

**Issue by noeppi-noeppi** [ChaoticTrials/Excavar#9]
### Minecraft version

1.18.1

### Excavar version

1.2.2

### Forge version

39.0.75

### The latest.log file

After asking, there is none

### Issue description

When you use a tool with only little bit of durability left, more blocks are highlighted for being broken than will actually be broken as the tool runs out of durability.

### Steps to reproduce

1. Get a pickaxe with only 3 durability left.
2. Mine some blocks (at least 4) using excavar. All will be highlighted but only 3 will be broken.

**Comment by MelanX** [comment]
I see a problem with this if the tool has an enchantment like unbreaking or custom enchantments which cause breaking the tool faster than normal. Any good solution idea for this? Otherwise, this can be closed and won't be fixed.

**Comment by noeppi-noeppi** [comment]
Make it a client side config option that is disabled by default so only people who want it can enable it?
